name: flutter_animarker
description: Solution to move a Marker smoothly throught Google Maps in Flutter.
version: 1.0.0
homepage: https://github.com/gauris26/flutter_animarker
repository: https://github.com/gauris26/clsflutter_animarker
publish_to: https://pub.dev
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.16.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.1
  google_maps_flutter_platform_interface: ^2.0.1
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter: null
