name: flutter_map_marker_animation
description: Solution to move a maker smoothly thought Google Maps in Flutter.
version: 0.0.2
homepage: https://gaurisjavier.com

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.16.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^0.5.21

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
